services:
  postgres:
    image: postgres:16
    container_name: postgres-booking
    restart: always
    environment:
      POSTGRES_USER: app-booking
      POSTGRES_PASSWORD: f0cHqjzNIVeRGQ==
      POSTGRES_DB: booking
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
